"""BUTTERFLY JOB — shared Blender asset kit.

Runs inside Blender 5.0.x (tested with the official `bpy` 5.0.1 module in background mode and
compatible with `blender -b -P <script>`).  Every visible 3D object of the game is generated by
functions in this package, saved as an editable .blend file and exported as a .glb.

Conventions
-----------
* 1 Blender unit = 1 game tile = 1 m.  Blender is Z-up; the glTF exporter converts to Y-up.
* Grid coordinates (x east, z south) map to Blender as  X = x - 15,  Y = 11 - z,  Z = height.
  Three.js therefore sees  X = x - 15,  Z = z - 11,  Y = height.
* Node names use `<asset>__<part>` (double underscore) because Three.js strips dots from names.
* Custom properties prefixed `bj_` are exported as glTF extras and summarised in the manifest:
  bj_role     variant | part | anchor | proxy | camera | dynamic | pivot
  bj_variant  stable variant id (conditions live in src/data/variants.json)
  bj_anim     transition style used by the runtime (fold, rise, unfurl, pop, flatten, none)
* Paper look: faces carry a vertex colour (palette + slight printed imperfection) multiplied with a
  tiling grey-scale print texture (grain, hatching, bricks, shingles, paving, cardboard edge).
"""
from __future__ import annotations

import json
import math
import os
import random
from typing import Iterable, Sequence

import bpy  # must come first: the bpy module registers bmesh/mathutils on import
import bmesh
import numpy as np
from mathutils import Matrix, Vector

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC_DIR = os.path.join(ROOT, 'blender', 'source')
GLB_DIR = os.path.join(ROOT, 'public', 'assets', 'models')
FONT_DIR = os.path.join(ROOT, 'blender', 'fonts')
DATA_DIR = os.path.join(ROOT, 'src', 'data')
MANIFEST_PARTS_DIR = os.path.join(ROOT, 'blender', 'build')

GRID_W, GRID_H = 30, 22
LEVEL_Y = {'S': -3.6, 'B': -2.0, 'G': 0.0, 'U': 2.0, 'R': 4.1}

# ---------------------------------------------------------------------------------------------
# Palette (sRGB).  Keep in sync with src/render/palette.ts for UI/overlay colours.
# ---------------------------------------------------------------------------------------------

def _hex(h: str):
    h = h.lstrip('#')
    return tuple(int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))

PAL = {k: _hex(v) for k, v in {
    'cream': '#EFE6D3', 'ivory': '#F6F0E2', 'paper': '#F3ECDD', 'card': '#D6C3A0',
    'card_dark': '#B9A27C', 'charcoal': '#3A393C', 'ink': '#2E2D30', 'slate': '#5C5F66',
    'slate_light': '#7B7F86', 'gray': '#9C9B96', 'warmgray': '#C3BBAB', 'stone': '#DCD2BF',
    'stone_dark': '#B9AE99', 'ochre': '#D2A04C', 'ochre_pale': '#E3C27F', 'teal': '#5E9A96',
    'teal_pale': '#9CC4BE', 'coral': '#E57560', 'coral_pale': '#EFA08E', 'amber': '#F0A63A',
    'red': '#D33B35', 'green': '#5E9E6A', 'sage': '#A7B792', 'sage_dark': '#8A9C77',
    'leaf1': '#8EA56A', 'leaf2': '#7A935E', 'leaf3': '#A3B47A', 'leaf4': '#6E8756',
    'leaf_young': '#B3C487', 'trunk': '#7B5E47', 'trunk_dark': '#5E4636', 'wood': '#A47C57',
    'wood_light': '#C59E73', 'glass': '#AFC2C6', 'glass_dark': '#8EA3A8', 'water': '#8CA5AC',
    'grass': '#AABD89', 'grass_dark': '#94A873', 'soil': '#9C846A', 'soil_dark': '#7F6A54',
    'brick': '#BC8667', 'brick_dark': '#9C6A51', 'navy': '#3E4B5E', 'beige': '#CDB794',
    'rust': '#A45E3E', 'white': '#FBF8F1', 'mustard': '#D9B44A', 'rose': '#D98E8A',
    'lilac': '#A99BC0', 'sky': '#9FB9C9', 'olive': '#8C8E5A', 'black': '#26262A',
    'concrete': '#B7B3AA', 'asphalt': '#8D8A85', 'pipe': '#8B8F8C', 'copper': '#B8784F',
}.items()}

# ---------------------------------------------------------------------------------------------
# Coordinates
# ---------------------------------------------------------------------------------------------

def W(x: float, z: float, y: float = 0.0) -> Vector:
    """Grid position (x east, z south, y up) → Blender world vector."""
    return Vector((x - GRID_W / 2, GRID_H / 2 - z, y))


def WT(x: int, z: int, y: float = 0.0) -> Vector:
    """Centre of tile (x, z)."""
    return W(x + 0.5, z + 0.5, y)


def to_three(v: Vector) -> list:
    """Blender vector → Three.js world coordinates (x, y, z)."""
    return [round(v.x, 4), round(v.z, 4), round(-v.y, 4)]

# ---------------------------------------------------------------------------------------------
# Scene management
# ---------------------------------------------------------------------------------------------

def reset_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = 'METRIC'
    scene.unit_settings.scale_length = 1.0
    scene.render.fps = 30
    _MATERIALS.clear()
    _TEXTURES.clear()
    _FONTS.clear()
    return scene


def collection(name: str, parent=None):
    col = bpy.data.collections.get(name)
    if col is None:
        col = bpy.data.collections.new(name)
        (parent or bpy.context.scene.collection).children.link(col)
    return col


def empty(name: str, loc: Vector = Vector((0, 0, 0)), parent=None, col=None, props: dict | None = None,
          display: str = 'PLAIN_AXES', size: float = 0.3):
    obj = bpy.data.objects.new(name, None)
    obj.empty_display_type = display
    obj.empty_display_size = size
    (col or bpy.context.scene.collection).objects.link(obj)
    if parent is not None:
        obj.parent = parent
        obj.location = loc - world_loc(parent)
    else:
        obj.location = loc
    for k, v in (props or {}).items():
        obj[k] = v
    return obj


def world_loc(obj) -> Vector:
    loc = Vector(obj.location)
    p = obj.parent
    while p is not None:
        loc += Vector(p.location)
        p = p.parent
    return loc


def set_props(obj, **props):
    for k, v in props.items():
        obj['bj_' + k] = v
    return obj

# ---------------------------------------------------------------------------------------------
# Procedural print textures (generated with numpy, packed into the .blend, embedded in the .glb)
# ---------------------------------------------------------------------------------------------

_TEXTURES: dict = {}
TEX_SIZE = 256


def _noise(size, scale, rng):
    """Tileable value noise via random low-res grid + bilinear upsample (wraps)."""
    n = max(2, size // scale)
    g = rng.random((n, n))
    xs = np.arange(size) * n / size
    x0 = np.floor(xs).astype(int) % n
    x1 = (x0 + 1) % n
    t = xs - np.floor(xs)
    t = t * t * (3 - 2 * t)
    a = g[x0][:, x0] * (1 - t)[None, :] + g[x0][:, x1] * t[None, :]
    b = g[x1][:, x0] * (1 - t)[None, :] + g[x1][:, x1] * t[None, :]
    return a * (1 - t)[:, None] + b * t[:, None]


def _paper_base(rng, size=TEX_SIZE, strength=1.0):
    img = np.ones((size, size), dtype=np.float32)
    img -= 0.035 * strength * _noise(size, 64, rng)
    img -= 0.030 * strength * _noise(size, 16, rng)
    img -= 0.020 * strength * _noise(size, 4, rng)
    # fibres: short random strokes
    for _ in range(int(140 * strength)):
        x, y = rng.integers(0, size, 2)
        ang = rng.random() * math.pi
        ln = rng.integers(4, 14)
        for i in range(ln):
            px = int(x + math.cos(ang) * i) % size
            py = int(y + math.sin(ang) * i) % size
            img[py, px] -= 0.045
    return img


def _draw_hline(img, y, thick, value, x0=0, x1=None):
    size = img.shape[0]
    x1 = size if x1 is None else x1
    for t in range(thick):
        yy = (y + t) % size
        img[yy, x0:x1] = np.minimum(img[yy, x0:x1], value)


def _draw_vline(img, x, thick, value, y0=0, y1=None):
    size = img.shape[0]
    y1 = size if y1 is None else y1
    for t in range(thick):
        xx = (x + t) % size
        img[y0:y1, xx] = np.minimum(img[y0:y1, xx], value)


def _make_texture(kind: str):
    rng = np.random.default_rng(sum(map(ord, kind)) * 7919)  # deterministic per texture kind
    s = TEX_SIZE
    img = _paper_base(rng)
    if kind == 'grain':
        pass
    elif kind == 'hatch':
        # fine diagonal façade hatching with printed irregularities
        for i in range(0, s * 2, 9):
            wob = rng.integers(-1, 2)
            for y in range(s):
                x = (i - y + wob) % s
                if rng.random() > 0.08:
                    img[y, x] = min(img[y, x], 0.86 + rng.random() * 0.04)
    elif kind == 'brick':
        course = 16
        for row, y in enumerate(range(0, s, course)):
            _draw_hline(img, y, 2, 0.80 + rng.random() * 0.05)
            off = 0 if row % 2 == 0 else 16
            for x in range(off, s + 32, 32):
                _draw_vline(img, x % s, 2, 0.82 + rng.random() * 0.05, y, min(s, y + course))
    elif kind == 'roof':
        course = 21
        for row, y in enumerate(range(0, s, course)):
            _draw_hline(img, y, 2, 0.74 + rng.random() * 0.05)
            off = 0 if row % 2 == 0 else 13
            for x in range(off, s + 26, 26):
                _draw_vline(img, x % s, 1, 0.80, y, min(s, y + course))
            # shading under each course
            for t in range(2, 6):
                img[(y + t) % s, :] *= 0.985
    elif kind == 'paving':
        cell = 32
        for y in range(0, s, cell):
            _draw_hline(img, y, 2, 0.80 + rng.random() * 0.04)
            off = 0 if (y // cell) % 2 == 0 else cell // 2
            for x in range(off, s + cell, cell):
                _draw_vline(img, x % s, 2, 0.80 + rng.random() * 0.04, y, min(s, y + cell))
    elif kind == 'cobble':
        cell = 21
        for y in range(0, s, cell):
            for x in range(0, s, cell):
                cx = x + rng.integers(-3, 4)
                cy = y + rng.integers(-3, 4)
                r = cell * 0.46
                for a in np.linspace(0, 2 * math.pi, 40):
                    px = int(cx + cell / 2 + math.cos(a) * r) % s
                    py = int(cy + cell / 2 + math.sin(a) * r * 0.85) % s
                    img[py, px] = min(img[py, px], 0.78)
    elif kind == 'edge':
        # corrugated cardboard: liner / flutes / liner across V (rows), repeating along U
        img = np.ones((s, s), dtype=np.float32) * 0.97
        img -= 0.03 * _noise(s, 16, rng)
        liner = int(s * 0.22)
        _draw_hline(img, liner, 3, 0.70)
        _draw_hline(img, s - liner - 3, 3, 0.70)
        mid0, mid1 = liner + 3, s - liner - 3
        amp = (mid1 - mid0) / 2 - 3
        centre = (mid0 + mid1) / 2
        for x in range(s):
            y = centre + amp * math.sin(x / s * math.pi * 2 * 8)
            yi = int(y)
            for t in range(-1, 2):
                img[(yi + t) % s, x] = min(img[(yi + t) % s, x], 0.72)
        img[mid0:mid1, :] *= 0.93
    elif kind == 'foliage':
        for _ in range(260):
            x, y = rng.integers(0, s, 2)
            ln = rng.integers(5, 12)
            ang = rng.random() * math.pi
            for i in range(ln):
                px = int(x + math.cos(ang) * i) % s
                py = int(y + math.sin(ang) * i) % s
                img[py, px] = min(img[py, px], 0.84)
    elif kind == 'wood':
        for y in range(0, s, 6):
            wob = rng.random() * 6
            for x in range(s):
                yy = int(y + 2 * math.sin(x / 23 + wob)) % s
                img[yy, x] = min(img[yy, x], 0.86)
    elif kind == 'grass':
        for _ in range(900):
            x, y = rng.integers(0, s, 2)
            for i in range(rng.integers(3, 7)):
                img[(y - i) % s, (x + i // 3) % s] = min(img[(y - i) % s, (x + i // 3) % s], 0.80)
    elif kind == 'plank':
        for y in range(0, s, 32):
            _draw_hline(img, y, 2, 0.78)
            for x in range(int(rng.integers(0, 64)), s, 96):
                _draw_vline(img, x, 2, 0.80, y, min(s, y + 32))
    elif kind == 'glass':
        img = np.ones((s, s), dtype=np.float32)
        img -= 0.05 * _noise(s, 64, rng)
        for i in range(0, s, 64):
            for y in range(s):
                x = (i + y // 2) % s
                for t in range(6):
                    img[y, (x + t) % s] = min(1.0, img[y, (x + t) % s] + 0.02)
    img = np.clip(img, 0, 1)
    rgba = np.ones((s, s, 4), dtype=np.float32)
    rgba[..., 0] = img
    rgba[..., 1] = img
    rgba[..., 2] = img * 0.995
    return rgba


def texture(kind: str):
    if kind in _TEXTURES:
        return _TEXTURES[kind]
    name = f'bj_tex_{kind}'
    img = bpy.data.images.get(name)
    if img is None:
        img = bpy.data.images.new(name, TEX_SIZE, TEX_SIZE, alpha=False)
        img.pixels.foreach_set(_make_texture(kind).ravel())
        img.file_format = 'PNG'
        img.filepath_raw = f'//textures/{name}.png'
        img.pack()
    _TEXTURES[kind] = img
    return img

# ---------------------------------------------------------------------------------------------
# Materials: vertex colour × print texture.  uv scale = texture repeats per metre.
# ---------------------------------------------------------------------------------------------

MATS = {
    'paper':   {'tex': 'grain',   'uv': 0.5,  'rough': 0.93},
    'wall':    {'tex': 'hatch',   'uv': 0.55, 'rough': 0.93},
    'brick':   {'tex': 'brick',   'uv': 0.5,  'rough': 0.95},
    'roof':    {'tex': 'roof',    'uv': 0.6,  'rough': 0.9},
    'paving':  {'tex': 'paving',  'uv': 0.35, 'rough': 0.95},
    'cobble':  {'tex': 'cobble',  'uv': 0.45, 'rough': 0.95},
    'edge':    {'tex': 'edge',    'uv': 1.0,  'rough': 0.95},
    'foliage': {'tex': 'foliage', 'uv': 0.8,  'rough': 0.9},
    'wood':    {'tex': 'wood',    'uv': 0.9,  'rough': 0.9},
    'grass':   {'tex': 'grass',   'uv': 0.45, 'rough': 0.97},
    'plank':   {'tex': 'plank',   'uv': 0.5,  'rough': 0.92},
    'glass':   {'tex': 'glass',   'uv': 0.6,  'rough': 0.35},
}
_MATERIALS: dict = {}


def material(key: str):
    if key in _MATERIALS:
        return _MATERIALS[key]
    spec = MATS[key]
    mat = bpy.data.materials.get('bj_' + key)
    if mat is None:
        mat = bpy.data.materials.new('bj_' + key)
        mat.use_nodes = True
        nt = mat.node_tree
        for n in list(nt.nodes):
            nt.nodes.remove(n)
        out = nt.nodes.new('ShaderNodeOutputMaterial')
        out.location = (500, 0)
        bsdf = nt.nodes.new('ShaderNodeBsdfPrincipled')
        bsdf.location = (200, 0)
        bsdf.inputs['Roughness'].default_value = spec['rough']
        bsdf.inputs['Metallic'].default_value = 0.0
        tex = nt.nodes.new('ShaderNodeTexImage')
        tex.location = (-400, 100)
        tex.image = texture(spec['tex'])
        tex.interpolation = 'Linear'
        vc = nt.nodes.new('ShaderNodeVertexColor')
        vc.location = (-400, -150)
        vc.layer_name = 'Col'
        mix = nt.nodes.new('ShaderNodeMix')
        mix.location = (-100, 0)
        mix.data_type = 'RGBA'
        mix.blend_type = 'MULTIPLY'
        mix.inputs[0].default_value = 1.0  # factor
        nt.links.new(tex.outputs['Color'], mix.inputs[6])
        nt.links.new(vc.outputs['Color'], mix.inputs[7])
        nt.links.new(mix.outputs[2], bsdf.inputs['Base Color'])
        nt.links.new(bsdf.outputs['BSDF'], out.inputs['Surface'])
        mat['bj_material'] = key
    _MATERIALS[key] = mat
    return mat

# ---------------------------------------------------------------------------------------------
# Mesh builder
# ---------------------------------------------------------------------------------------------

class MB:
    """Accumulates flat-shaded faces with material, per-face colour and UVs."""

    def __init__(self, seed: int = 1, jitter: float = 0.035):
        self.verts: list = []
        self.faces: list = []   # (vertex indices, material key, rgb, uvs|None)
        self.rng = random.Random(seed)
        self.jitter = jitter

    # -- primitive faces ------------------------------------------------------------------
    def face(self, pts: Sequence, mat: str, col, uvs=None, vary: bool = True):
        base = len(self.verts)
        self.verts.extend(tuple(p) for p in pts)
        c = tuple(col)
        if vary and self.jitter > 0:
            k = 1.0 + (self.rng.random() - 0.5) * 2 * self.jitter
            c = tuple(min(1.0, max(0.0, ch * k)) for ch in c)
        self.faces.append((list(range(base, base + len(pts))), mat, c, uvs))
        return self

    def quad(self, a, b, c, d, mat, col, uvs=None, vary=True):
        return self.face([a, b, c, d], mat, col, uvs, vary)

    def merge(self, other: 'MB', matrix: Matrix | None = None):
        base = len(self.verts)
        for v in other.verts:
            self.verts.append(tuple(matrix @ Vector(v)) if matrix is not None else v)
        for idx, mat, col, uvs in other.faces:
            self.faces.append(([i + base for i in idx], mat, col, uvs))
        return self

    def transformed(self, matrix: Matrix) -> 'MB':
        out = MB(jitter=0)
        out.merge(self, matrix)
        return out

    # -- solids ---------------------------------------------------------------------------
    def box(self, x0, y0, z0, x1, y1, z1, mat, col, edge: str | None = 'edge', edge_col=None,
            skip: Iterable[str] = ()):
        """Axis-aligned box in Blender coords.  The thinnest axis is treated as the paper
        thickness: the two faces across it use `mat`, the four cut faces use the cardboard edge."""
        x0, x1 = min(x0, x1), max(x0, x1)
        y0, y1 = min(y0, y1), max(y0, y1)
        z0, z1 = min(z0, z1), max(z0, z1)
        dims = (x1 - x0, y1 - y0, z1 - z0)
        thin = dims.index(min(dims))
        edge_col = edge_col or PAL['card']
        P = lambda x, y, z: (x, y, z)
        faces = {
            '+z': [P(x0, y0, z1), P(x1, y0, z1), P(x1, y1, z1), P(x0, y1, z1)],
            '-z': [P(x0, y1, z0), P(x1, y1, z0), P(x1, y0, z0), P(x0, y0, z0)],
            '+x': [P(x1, y0, z0), P(x1, y1, z0), P(x1, y1, z1), P(x1, y0, z1)],
            '-x': [P(x0, y1, z0), P(x0, y0, z0), P(x0, y0, z1), P(x0, y1, z1)],
            '+y': [P(x1, y1, z0), P(x0, y1, z0), P(x0, y1, z1), P(x1, y1, z1)],
            '-y': [P(x0, y0, z0), P(x1, y0, z0), P(x1, y0, z1), P(x0, y0, z1)],
        }
        axis_of = {'+x': 0, '-x': 0, '+y': 1, '-y': 1, '+z': 2, '-z': 2}
        for key, pts in faces.items():
            if key in skip:
                continue
            if edge is None or axis_of[key] == thin or min(dims) > 0.35:
                self.face(pts, mat, col)
            else:
                self.face(pts, edge, edge_col, uvs=_edge_uvs(pts, thin, (x0, y0, z0), dims))
        return self

    def panel(self, origin: Vector, u: Vector, v: Vector, thickness: float, mat: str, col,
              back_mat: str | None = None, back_col=None, edge: str = 'edge', edge_col=None):
        """Arbitrarily oriented paper panel: parallelogram origin+u+v extruded by `thickness`
        along -normal.  Front uses `mat`, back `back_mat`, the rim uses the cardboard edge."""
        n = u.cross(v).normalized()
        o = Vector(origin)
        a, b, c, d = o, o + u, o + u + v, o + v
        off = -n * thickness
        a2, b2, c2, d2 = a + off, b + off, c + off, d + off
        uu, vv = u.length, v.length
        s = MATS[mat]['uv']
        self.face([a, b, c, d], mat, col, uvs=[(0, 0), (uu * s, 0), (uu * s, vv * s), (0, vv * s)])
        bm_ = back_mat or mat
        sb = MATS[bm_]['uv']
        self.face([b2, a2, d2, c2], bm_, back_col or col,
                  uvs=[(uu * sb, 0), (0, 0), (0, vv * sb), (uu * sb, vv * sb)])
        ec = edge_col or PAL['card']
        for p, q, L in ((a, b, uu), (b, c, vv), (c, d, uu), (d, a, vv)):
            self.face([p, q, q + off, p + off], edge, ec, uvs=[(0, 0), (L, 0), (L, 1), (0, 1)])
        return self

    def prism(self, pts2d: Sequence, z0: float, z1: float, mat: str, col, side_mat=None, side_col=None,
              cap_top=True, cap_bottom=True):
        """Vertical extrusion of a convex/concave polygon (counter-clockwise, Blender XY)."""
        top = [(x, y, z1) for x, y in pts2d]
        bot = [(x, y, z0) for x, y in pts2d]
        if cap_top:
            self.face(top, mat, col)
        if cap_bottom:
            self.face(list(reversed(bot)), mat, col)
        sm = side_mat or mat
        sc = side_col or col
        n = len(pts2d)
        for i in range(n):
            j = (i + 1) % n
            self.face([bot[i], bot[j], top[j], top[i]], sm, sc)
        return self

    def cylinder(self, centre: Vector, r0: float, r1: float, h: float, sides: int, mat: str, col,
                 cap=True, rot: float = 0.0, cap_col=None):
        c = Vector(centre)
        ring0 = [c + Vector((math.cos(rot + i / sides * 2 * math.pi) * r0,
                             math.sin(rot + i / sides * 2 * math.pi) * r0, 0)) for i in range(sides)]
        ring1 = [c + Vector((math.cos(rot + i / sides * 2 * math.pi) * r1,
                             math.sin(rot + i / sides * 2 * math.pi) * r1, h)) for i in range(sides)]
        for i in range(sides):
            j = (i + 1) % sides
            self.face([ring0[i], ring0[j], ring1[j], ring1[i]], mat, col)
        if cap:
            self.face(ring1, mat, cap_col or col)
            self.face(list(reversed(ring0)), mat, cap_col or col)
        return self

    def blob(self, centre: Vector, radius: Vector, mat: str, cols: Sequence, subdiv: int = 1,
             seed: int = 0, rough: float = 0.16, flat_bottom: float | None = None):
        """Faceted low-poly foliage cluster (jittered icosphere)."""
        rng = random.Random(seed)
        bm = bmesh.new()
        bmesh.ops.create_icosphere(bm, subdivisions=subdiv, radius=1.0)
        for v in bm.verts:
            d = 1.0 + (rng.random() - 0.5) * 2 * rough
            v.co = Vector((v.co.x * radius.x * d, v.co.y * radius.y * d, v.co.z * radius.z * d))
            if flat_bottom is not None and v.co.z < -radius.z * flat_bottom:
                v.co.z = -radius.z * flat_bottom + (v.co.z + radius.z * flat_bottom) * 0.25
        for f in bm.faces:
            pts = [Vector(centre) + v.co for v in f.verts]
            # lighter facets on top, darker below: printed imperfection
            up = f.normal.z
            col = cols[rng.randrange(len(cols))]
            shade = 1.0 + 0.06 * up
            self.face(pts, mat, tuple(min(1.0, ch * shade) for ch in col))
        bm.free()
        return self

    def wall(self, p0: Vector, p1: Vector, z0: float, z1: float, thickness: float,
             holes: Sequence = (), out_mat='wall', out_col=None, in_mat='paper', in_col=None,
             edge_col=None, centered=True, reveal_col=None):
        """Wall from p0 to p1 (Blender XY, horizontal) between heights z0..z1.
        Outside face is on the right of p0→p1 (i.e. -normal side where normal = up × dir).
        holes: (u0, u1, v0, v1) in metres along the wall (u) and up from z0 (v)."""
        p0 = Vector((p0.x, p0.y, 0))
        p1 = Vector((p1.x, p1.y, 0))
        d = (p1 - p0)
        L = d.length
        dn = d.normalized()
        right = Vector((dn.y, -dn.x, 0))   # outside direction
        H = z1 - z0
        t = thickness
        o_off = right * (t / 2 if centered else t)
        i_off = -right * (t / 2 if centered else 0)
        out_col = out_col or PAL['cream']
        in_col = in_col or PAL['ivory']
        edge_col = edge_col or PAL['card']
        reveal_col = reveal_col or edge_col
        us = sorted({0.0, L} | {h[0] for h in holes} | {h[1] for h in holes})
        vs = sorted({0.0, H} | {h[2] for h in holes} | {h[3] for h in holes})

        def inside_hole(u, v):
            return any(h[0] <= u <= h[1] and h[2] <= v <= h[3] for h in holes)

        def P(u, v, side):
            base = p0 + dn * u + Vector((0, 0, z0 + v))
            return base + (o_off if side == 'o' else i_off)

        so = MATS[out_mat]['uv']
        si = MATS[in_mat]['uv']
        for a in range(len(us) - 1):
            for b in range(len(vs) - 1):
                u0, u1, v0, v1 = us[a], us[a + 1], vs[b], vs[b + 1]
                if inside_hole((u0 + u1) / 2, (v0 + v1) / 2):
                    continue
                # outside face (facing `right`)
                self.face([P(u1, v0, 'o'), P(u0, v0, 'o'), P(u0, v1, 'o'), P(u1, v1, 'o')], out_mat, out_col,
                          uvs=[(-u1 * so, (z0 + v0) * so), (-u0 * so, (z0 + v0) * so),
                               (-u0 * so, (z0 + v1) * so), (-u1 * so, (z0 + v1) * so)])
                self.face([P(u0, v0, 'i'), P(u1, v0, 'i'), P(u1, v1, 'i'), P(u0, v1, 'i')], in_mat, in_col,
                          uvs=[(u0 * si, (z0 + v0) * si), (u1 * si, (z0 + v0) * si),
                               (u1 * si, (z0 + v1) * si), (u0 * si, (z0 + v1) * si)])
        # rim: top, bottom, ends
        def rim(pa, pb, L_):
            self.face([pa[0], pb[0], pb[1], pa[1]], 'edge', edge_col,
                      uvs=[(0, 0), (L_, 0), (L_, 1), (0, 1)])
        # top edge (split around holes touching the top)
        top_segments = _segments(0, L, [(h[0], h[1]) for h in holes if h[3] >= H - 1e-6])
        for s0, s1 in top_segments:
            rim((P(s1, H, 'i'), P(s1, H, 'o')), (P(s0, H, 'i'), P(s0, H, 'o')), s1 - s0)
        bot_segments = _segments(0, L, [(h[0], h[1]) for h in holes if h[2] <= 1e-6])
        for s0, s1 in bot_segments:
            rim((P(s0, 0, 'i'), P(s0, 0, 'o')), (P(s1, 0, 'i'), P(s1, 0, 'o')), s1 - s0)
        self.face([P(0, 0, 'o'), P(0, 0, 'i'), P(0, H, 'i'), P(0, H, 'o')], 'edge', edge_col,
                  uvs=[(0, 0), (0, 1), (H, 1), (H, 0)])
        self.face([P(L, 0, 'i'), P(L, 0, 'o'), P(L, H, 'o'), P(L, H, 'i')], 'edge', edge_col,
                  uvs=[(0, 1), (0, 0), (H, 0), (H, 1)])
        # hole reveals
        for u0, u1, v0, v1 in holes:
            if v0 > 1e-6:   # sill
                self.face([P(u0, v0, 'o'), P(u1, v0, 'o'), P(u1, v0, 'i'), P(u0, v0, 'i')], 'edge', reveal_col,
                          uvs=[(0, 0), (u1 - u0, 0), (u1 - u0, 1), (0, 1)])
            if v1 < H - 1e-6:  # head
                self.face([P(u0, v1, 'i'), P(u1, v1, 'i'), P(u1, v1, 'o'), P(u0, v1, 'o')], 'edge', reveal_col,
                          uvs=[(0, 1), (u1 - u0, 1), (u1 - u0, 0), (0, 0)])
            self.face([P(u0, v0, 'i'), P(u0, v0, 'o'), P(u0, v1, 'o'), P(u0, v1, 'i')], 'edge', reveal_col,
                      uvs=[(0, 1), (0, 0), (v1 - v0, 0), (v1 - v0, 1)])
            self.face([P(u1, v0, 'o'), P(u1, v0, 'i'), P(u1, v1, 'i'), P(u1, v1, 'o')], 'edge', reveal_col,
                      uvs=[(0, 0), (0, 1), (v1 - v0, 1), (v1 - v0, 0)])
        return self

    # -- output -----------------------------------------------------------------------------
    def build(self, name: str, pivot: Vector | None = None, parent=None, col=None, props: dict | None = None):
        if not self.faces:
            obj = empty(name, pivot if pivot is not None else Vector((0, 0, 0)), parent=parent, col=col, props=props)
            return obj
        pivot = Vector(pivot) if pivot is not None else Vector((0, 0, 0))
        mesh = bpy.data.meshes.new(name)
        verts = [(v[0] - pivot.x, v[1] - pivot.y, v[2] - pivot.z) for v in self.verts]
        faces = [f[0] for f in self.faces]
        mesh.from_pydata(verts, [], faces)
        mesh.update(calc_edges=True)
        mat_keys = []
        for f in self.faces:
            if f[1] not in mat_keys:
                mat_keys.append(f[1])
        for k in mat_keys:
            mesh.materials.append(material(k))
        mesh.polygons.foreach_set('material_index', [mat_keys.index(f[1]) for f in self.faces])
        mesh.polygons.foreach_set('use_smooth', [False] * len(self.faces))
        # per-corner colour + uv
        colors = []
        uvs = []
        for idx, mat, rgb, fuv in self.faces:
            pts = [self.verts[i] for i in idx]
            if fuv is None:
                fuv = _box_uvs(pts, MATS[mat]['uv'])
            for k in range(len(idx)):
                colors.extend((rgb[0], rgb[1], rgb[2], 1.0))
                uvs.extend(fuv[k])
        ca = mesh.color_attributes.new(name='Col', type='BYTE_COLOR', domain='CORNER')
        ca.data.foreach_set('color_srgb', colors)
        mesh.color_attributes.active_color = ca
        mesh.color_attributes.render_color_index = 0
        uvl = mesh.uv_layers.new(name='UVMap')
        uvl.uv.foreach_set('vector', uvs)
        mesh.validate(clean_customdata=False)
        obj = bpy.data.objects.new(name, mesh)
        (col or bpy.context.scene.collection).objects.link(obj)
        if parent is not None:
            obj.parent = parent
            obj.location = pivot - world_loc(parent)
        else:
            obj.location = pivot
        for k, v in (props or {}).items():
            obj[k] = v
        return obj


def _segments(a, b, cuts):
    """Split [a,b] removing the given (c0,c1) intervals."""
    out = [(a, b)]
    for c0, c1 in cuts:
        nxt = []
        for s0, s1 in out:
            if c1 <= s0 or c0 >= s1:
                nxt.append((s0, s1))
                continue
            if c0 > s0:
                nxt.append((s0, c0))
            if c1 < s1:
                nxt.append((c1, s1))
        out = nxt
    return [s for s in out if s[1] - s[0] > 1e-6]


def _box_uvs(pts, scale):
    a, b, c = Vector(pts[0]), Vector(pts[1]), Vector(pts[2])
    n = (b - a).cross(c - a)
    ax = max(range(3), key=lambda i: abs(n[i]))
    out = []
    for p in pts:
        if ax == 2:
            out.append((p[0] * scale, p[1] * scale))
        elif ax == 0:
            out.append((p[1] * scale * (1 if n[0] > 0 else -1), p[2] * scale))
        else:
            out.append((p[0] * scale * (-1 if n[1] > 0 else 1), p[2] * scale))
    return out


def _edge_uvs(pts, thin_axis, lo, dims):
    """Cardboard edge: V spans the paper thickness 0..1, U runs along the edge (metres)."""
    out = []
    t = dims[thin_axis] or 1.0
    for p in pts:
        v = (p[thin_axis] - lo[thin_axis]) / t
        # along = largest remaining axis coordinate
        others = [i for i in range(3) if i != thin_axis]
        along = max(others, key=lambda i: dims[i])
        out.append((p[along], v))
    return out

# ---------------------------------------------------------------------------------------------
# Text (cut-out paper letters).  Uses Liberation Serif (SIL OFL), packed into every .blend.
# ---------------------------------------------------------------------------------------------

_FONTS: dict = {}


def font(bold=True):
    key = 'bold' if bold else 'regular'
    if key in _FONTS:
        return _FONTS[key]
    path = os.path.join(FONT_DIR, 'LiberationSerif-Bold.ttf' if bold else 'LiberationSerif-Regular.ttf')
    f = bpy.data.fonts.load(path, check_existing=True)
    f.pack()
    _FONTS[key] = f
    return f


def text_mb(text: str, size: float, depth: float, col, mat='paper', bold=True, align='CENTER',
            spacing: float = 1.0) -> MB:
    """Returns an MB with extruded letters laid out on the XZ plane (reading along +X, facing -Y),
    baseline at z=0, centred on x=0."""
    curve = bpy.data.curves.new('tmp_text', type='FONT')
    curve.body = text
    curve.font = font(bold)
    curve.size = size
    curve.extrude = depth / 2
    curve.resolution_u = 2
    curve.align_x = align
    curve.space_character = spacing
    curve.fill_mode = 'BOTH'
    obj = bpy.data.objects.new('tmp_text', curve)
    bpy.context.scene.collection.objects.link(obj)
    dg = bpy.context.evaluated_depsgraph_get()
    me = bpy.data.meshes.new_from_object(obj.evaluated_get(dg))
    bm = bmesh.new()
    bm.from_mesh(me)
    rot = Matrix.Rotation(math.pi / 2, 4, 'X')   # text XY plane → XZ plane, facing -Y
    bm.transform(rot)
    mb = MB(jitter=0)
    for f in bm.faces:
        pts = [v.co.copy() for v in f.verts]
        if abs(f.normal.y) > 0.5:
            mb.face(pts, mat, col, vary=False)
        else:
            mb.face(pts, 'edge', PAL['card'], vary=False)
    bm.free()
    bpy.data.objects.remove(obj)
    bpy.data.curves.remove(curve)
    bpy.data.meshes.remove(me)
    return mb

# ---------------------------------------------------------------------------------------------
# Transforms
# ---------------------------------------------------------------------------------------------

def rot_z(deg: float, about: Vector | None = None) -> Matrix:
    m = Matrix.Rotation(math.radians(deg), 4, 'Z')
    if about is None:
        return m
    return Matrix.Translation(about) @ m @ Matrix.Translation(-Vector(about))


def translate(v: Vector) -> Matrix:
    return Matrix.Translation(Vector(v))

# ---------------------------------------------------------------------------------------------
# Export + manifest
# ---------------------------------------------------------------------------------------------

def add_preview_rig(target: Vector = Vector((0, 0, 0)), dist: float = 40.0):
    """Camera + sun so the .blend opens with a sensible view (not exported)."""
    cam_data = bpy.data.cameras.new('preview_cam')
    cam_data.type = 'ORTHO'
    cam_data.ortho_scale = dist
    cam = bpy.data.objects.new('preview_cam', cam_data)
    bpy.context.scene.collection.objects.link(cam)
    cam.location = Vector(target) + Vector((dist * 0.62, -dist * 0.62, dist * 0.55))
    direction = Vector(target) - cam.location
    cam.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()
    bpy.context.scene.camera = cam
    sun_data = bpy.data.lights.new('preview_sun', 'SUN')
    sun_data.energy = 3.0
    sun = bpy.data.objects.new('preview_sun', sun_data)
    sun.rotation_euler = (math.radians(50), 0, math.radians(35))
    bpy.context.scene.collection.objects.link(sun)


def save_and_export(asset: str, notes: str = ''):
    os.makedirs(SRC_DIR, exist_ok=True)
    os.makedirs(GLB_DIR, exist_ok=True)
    os.makedirs(MANIFEST_PARTS_DIR, exist_ok=True)
    blend_path = os.path.join(SRC_DIR, f'{asset}.blend')
    glb_path = os.path.join(GLB_DIR, f'{asset}.glb')
    bpy.context.scene['bj_asset'] = asset
    bpy.context.scene['bj_notes'] = notes
    try:
        bpy.ops.file.pack_all()
    except Exception as exc:  # pragma: no cover - diagnostics only
        print('pack_all failed:', exc)
    bpy.ops.wm.save_as_mainfile(filepath=blend_path, compress=True)
    export_glb(glb_path)
    part = manifest_part(asset, glb_path, blend_path)
    with open(os.path.join(MANIFEST_PARTS_DIR, f'{asset}.json'), 'w') as fh:
        json.dump(part, fh, indent=1)
    print(f'[bj] {asset}: {part["stats"]["objects"]} objects, {part["stats"]["triangles"]} tris, '
          f'{os.path.getsize(glb_path) / 1024:.0f} KB glb')
    return part


def export_glb(glb_path: str):
    """Project-wide glTF export settings.

    * No normals: every surface is flat-shaded paper; Three.js derives facet normals in the
      fragment shader (GLTFLoader enables flatShading for meshes without NORMAL).
    * Draco geometry compression + WEBP textures (EXT_texture_webp) keep downloads small; the
      Draco WASM decoder ships locally in public/draco/.
    * Custom properties → glTF extras (bj_* roles), vertex colours → COLOR_0.
    """
    bpy.ops.export_scene.gltf(
        filepath=glb_path,
        export_format='GLB',
        export_yup=True,
        export_apply=True,
        export_texcoords=True,
        export_normals=False,
        export_vertex_color='ACTIVE',
        export_all_vertex_colors=False,
        export_materials='EXPORT',
        export_image_format='WEBP',
        export_image_quality=82,
        export_extras=True,
        export_cameras=False,
        export_lights=False,
        export_animations=True,
        export_animation_mode='ACTIONS',
        export_skins=True,
        export_morph=False,
        export_optimize_animation_size=True,
        export_draco_mesh_compression_enable=True,
        export_draco_mesh_compression_level=7,
        export_draco_position_quantization=14,
        export_draco_texcoord_quantization=12,
        export_draco_color_quantization=8,
        export_draco_generic_quantization=12,
    )


def _tri_count(obj):
    if obj.type != 'MESH':
        return 0
    return sum(len(p.vertices) - 2 for p in obj.data.polygons)


def _bounds_three(obj):
    if obj.type != 'MESH':
        return None
    mw = obj.matrix_world
    pts = [mw @ Vector(c) for c in obj.bound_box]
    mn = [min(p[i] for p in pts) for i in range(3)]
    mx = [max(p[i] for p in pts) for i in range(3)]
    # blender (x,y,z) → three (x, z, -y)
    return {'min': [round(mn[0], 3), round(mn[2], 3), round(-mx[1], 3)],
            'max': [round(mx[0], 3), round(mx[2], 3), round(-mn[1], 3)]}


def manifest_part(asset: str, glb_path: str, blend_path: str) -> dict:
    bpy.context.view_layer.update()
    nodes = []
    tris = 0
    for obj in bpy.data.objects:
        if obj.name.startswith('preview_'):
            continue
        tris += _tri_count(obj)
        props = {k[3:]: _jsonable(obj[k]) for k in obj.keys() if k.startswith('bj_')}
        if not props:
            continue
        entry = {'node': obj.name, **props}
        if obj.parent is not None:
            entry['parent'] = obj.parent.name
        mw = obj.matrix_world
        entry['position'] = to_three(mw.translation)
        b = _subtree_bounds(obj)
        if b:
            entry['bounds'] = b
        nodes.append(entry)
    anims = [a.name for a in bpy.data.actions]
    return {
        'asset': asset,
        'file': f'assets/models/{asset}.glb',
        'source': f'blender/source/{asset}.blend',
        'blender': bpy.app.version_string,
        'stats': {'objects': len([o for o in bpy.data.objects if not o.name.startswith('preview_')]),
                  'triangles': tris,
                  'materials': sorted(m.name for m in bpy.data.materials if m.users),
                  'images': sorted(i.name for i in bpy.data.images if i.users),
                  'glb_bytes': os.path.getsize(glb_path)},
        'nodes': nodes,
        'animations': anims,
    }


def _subtree_bounds(obj):
    mins, maxs = None, None
    stack = [obj]
    while stack:
        o = stack.pop()
        b = _bounds_three(o)
        if b:
            mins = b['min'] if mins is None else [min(a, c) for a, c in zip(mins, b['min'])]
            maxs = b['max'] if maxs is None else [max(a, c) for a, c in zip(maxs, b['max'])]
        stack.extend(o.children)
    if mins is None:
        return None
    return {'min': mins, 'max': maxs}


def _jsonable(v):
    if isinstance(v, (int, float, str, bool)):
        return v
    try:
        return v.to_list()
    except AttributeError:
        pass
    try:
        return [x for x in v]
    except TypeError:
        return str(v)


def load_json(name: str):
    with open(os.path.join(DATA_DIR, name)) as fh:
        return json.load(fh)


_VARIANT_IDS: set | None = None
_LAYOUT: dict | None = None


def variant_ids() -> set:
    global _VARIANT_IDS
    if _VARIANT_IDS is None:
        _VARIANT_IDS = set(load_json('variants.json')['variants'].keys())
    return _VARIANT_IDS


def layout() -> dict:
    global _LAYOUT
    if _LAYOUT is None:
        _LAYOUT = load_json('layout.json')
    return _LAYOUT


def vroot(name: str, vid: str, loc: Vector | None = None, anim: str = 'fold', col=None, parent=None, **extra):
    """Variant root node.  `vid` must be registered in src/data/variants.json."""
    if vid not in variant_ids():
        raise KeyError(f'variant "{vid}" is not registered in src/data/variants.json')
    props = {'bj_role': 'variant', 'bj_variant': vid, 'bj_anim': anim}
    for k, v in extra.items():
        props['bj_' + k] = v
    return empty(name, loc if loc is not None else Vector((0, 0, 0)), parent=parent, col=col, props=props)


def group(name: str, parent=None, col=None, loc: Vector | None = None, **extra):
    """Plain grouping node (optionally tagged with bj_* metadata such as level/side/building)."""
    props = {('bj_' + k): v for k, v in extra.items()}
    return empty(name, loc if loc is not None else Vector((0, 0, 0)), parent=parent, col=col, props=props or None)


def rect_box(mb: 'MB', x0, z0, x1, z1, y0, y1, mat, col, inset=0.0, edge='edge', edge_col=None):
    """Axis-aligned box covering the inclusive tile rect (grid coords), heights y0..y1."""
    a = W(x0 + inset, z1 + 1 - inset)
    b = W(x1 + 1 - inset, z0 + inset)
    mb.box(a.x, a.y, y0, b.x, b.y, y1, mat, col, edge=edge, edge_col=edge_col)
    return mb


def anchor(name: str, anchor_id: str, loc: Vector, parent=None, col=None, **extra):
    """Non-rendered helper node marking an interaction point / entrance / landing."""
    props = {'bj_role': 'anchor', 'bj_anchor': anchor_id}
    for k, v in extra.items():
        props['bj_' + k] = v
    return empty(name, loc, parent=parent, col=col, props=props, display='SPHERE', size=0.12)


def proxy(name: str, proxy_id: str, center: Vector, size: Vector, parent=None, col=None, **extra):
    """Lightweight collision / pick proxy exported as metadata (an empty with its box size)."""
    props = {'bj_role': 'proxy', 'bj_proxy': proxy_id, 'bj_size': [round(size.x, 3), round(size.z, 3), round(size.y, 3)]}
    for k, v in extra.items():
        props['bj_' + k] = v
    return empty(name, center, parent=parent, col=col, props=props, display='CUBE', size=0.5)
