import * as THREE from 'three';
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
import { applyPaper } from './paper';

/** Entry of public/assets/manifest.json (generated by blender/scripts/build_all.py). */
export interface ManifestNode {
  node: string;
  role: string;
  variant?: string;
  anim?: string;
  order?: number;
  anchor?: string;
  parent?: string;
  position: [number, number, number];
  bounds?: { min: [number, number, number]; max: [number, number, number] };
  [key: string]: unknown;
}

export interface ManifestAsset {
  asset: string;
  file: string;
  source: string;
  blender: string;
  stats: { objects: number; triangles: number; materials: string[]; images: string[]; glb_bytes: number };
  nodes: ManifestNode[];
  animations: string[];
}

export interface Manifest {
  version: number;
  generated: string;
  blender: string;
  assets: Record<string, ManifestAsset>;
}

export type AssetLoadProgress = (loaded: number, total: number, label: string) => void;

/**
 * Loads Blender-exported .glb files once and keeps them cached for the lifetime of the page.
 * Era switches and contract restarts only toggle/clone cached scenes; nothing is re-downloaded
 * or re-parsed.  Missing or failing files raise an AssetError naming the file.
 */
export class AssetError extends Error {
  constructor(public readonly file: string, message: string) {
    super(message);
  }
}

export class AssetLibrary {
  private readonly loader: GLTFLoader;
  private readonly draco: DRACOLoader;
  private readonly cache = new Map<string, Promise<GLTF>>();
  private readonly resolved = new Map<string, GLTF>();
  manifest: Manifest | null = null;
  loads = 0;

  constructor(private readonly baseUrl: string = './', private readonly anisotropy = 4) {
    this.draco = new DRACOLoader();
    this.draco.setDecoderPath(`${baseUrl}draco/`);
    this.loader = new GLTFLoader();
    this.loader.setDRACOLoader(this.draco);
  }

  async loadManifest(): Promise<Manifest> {
    if (this.manifest) return this.manifest;
    const url = `${this.baseUrl}assets/manifest.json`;
    let res: Response;
    try {
      res = await fetch(url);
    } catch (err) {
      throw new AssetError(url, `Could not reach ${url}: ${(err as Error).message}`);
    }
    if (!res.ok) throw new AssetError(url, `Asset manifest missing (${res.status}) at ${url}`);
    this.manifest = (await res.json()) as Manifest;
    return this.manifest;
  }

  load(asset: string): Promise<GLTF> {
    const hit = this.cache.get(asset);
    if (hit) return hit;
    const entry = this.manifest?.assets[asset];
    const file = entry ? entry.file : `assets/models/${asset}.glb`;
    const url = `${this.baseUrl}${file}`;
    const p = new Promise<GLTF>((resolve, reject) => {
      this.loads += 1;
      this.loader.load(
        url,
        (gltf) => {
          applyPaper(gltf.scene, this.anisotropy);
          this.resolved.set(asset, gltf);
          resolve(gltf);
        },
        undefined,
        (err) => reject(new AssetError(url, `Failed to load ${url}: ${(err as Error)?.message ?? err}`)),
      );
    });
    this.cache.set(asset, p);
    // allow a retry after a failure
    p.catch(() => this.cache.delete(asset));
    return p;
  }

  async loadAll(assets: string[], onProgress?: AssetLoadProgress): Promise<void> {
    let done = 0;
    onProgress?.(0, assets.length, '');
    await Promise.all(
      assets.map((a) =>
        this.load(a).then(() => {
          done += 1;
          onProgress?.(done, assets.length, a);
        }),
      ),
    );
  }

  get(asset: string): GLTF {
    const g = this.resolved.get(asset);
    if (!g) throw new AssetError(asset, `Asset ${asset} used before it finished loading`);
    return g;
  }

  /** Every asset's scene is used exactly once in the diorama; repeated props are cloned. */
  scene(asset: string): THREE.Group {
    return this.get(asset).scene;
  }

  clips(asset: string): THREE.AnimationClip[] {
    return this.get(asset).animations;
  }

  dispose(): void {
    this.draco.dispose();
  }
}

/** Find a node by its Blender name (Three.js keeps `__` intact; dots would be stripped). */
export function findNode(root: THREE.Object3D, name: string): THREE.Object3D | null {
  return root.getObjectByName(name) ?? null;
}
